version: "3"
services:
    mongo:
        image: mongo:3.2.21-jessie
        restart: always
        command: mongod --bind_ip 0.0.0.0
        ports:
            - 27017:27017
        volumes:
            - ./data:/data
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password
    tenants:
        build: ./tenants
        restart: always
        ports:
            - 8080:8080
        volumes:
            - ./tenants:/tenants
            - ./tenants/node_modules
        depends_on:
            - mongo
        environment:
            DB_USER: root
            DB_PASSWORD: password
            DB_URI: 192.168.99.100:27017