version: "3"
services:
    mongo:
        image: mongo:3.2.21-jessie
        restart: always
        command: mongod --bind_ip 0.0.0.0
        ports:
            - 27017:27017
        volumes:
            - ./data:/data
        environment:
            MONGO_INITDB_ROOT_USERNAME: borrowland
            MONGO_INITDB_ROOT_PASSWORD: password
    etcd:
        image: quay.io/coreos/etcd:latest
        restart: always
        ports:
            - 2376:2376
        volumes:
            - ./etcd-data:/etcd-data
        command: >-
            /usr/local/bin/etcd
            -name node1
            -advertise-client-urls http://etcd:2376
            -listen-client-urls http://0.0.0.0:2376
            -initial-advertise-peer-urls http://etcd:2380
            -listen-peer-urls http://0.0.0.0:2380
            -initial-cluster node1=http://etcd:2380
            -cors="*"

    tenants:
        #image: mkoplan/tenants:0.5
        build: ./tenants
        restart: always
        ports:
            - 8080:8080
        volumes:
            - ./tenants:/tenants
        depends_on:
            - mongo
            - etcd
        environment:
            ENVIRONMENT: dev
            VERSION: v1
            DB_USER: borrowland
            DB_PASSWORD: password
            DB_URI: mongo:27017
            ETCD_URL: etcd:2376
            HOST: tenants
            HOST_PORT: 8080
            ETCD_EQUIPMENTENABLED: "false"
    leasing:
        #image: mkoplan/leasing:0.0.1
        build: ./leasing
        restart: always
        ports:
            - 8082:8080
        volumes:
            - ./tenants:/tenants
        depends_on:
            - mongo
            - etcd
        environment:
            ENVIRONMENT: dev
            VERSION: v1
            DB_USER: borrowland
            DB_PASSWORD: password
            DB_URI: mongo:27017
            ETCD_URL: etcd:2376
            HOST: leasing
            HOST_PORT: 8080
            ETCD_EQUIPMENTENABLED: "false"

    equipment:
        #image: mkoplan/equipment:0.5
        build: ./equipment
        restart: always
        ports:
            - 8081:8080
        volumes:
            - ./equipment:/equipment
        depends_on:
            - mongo
            - etcd
        environment:
            ENVIRONMENT: dev
            VERSION: v1
            HOST: equipment
            HOST_PORT: 8080
            DB_USER: borrowland
            DB_PASSWORD: password
            DB_URI: mongo:27017
            ETCD_URL: etcd:2376
            ETCD_NUMEQUIPMENTPERTENANTGET: 20
