apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: etcd
  name: etcd
spec:
  type: NodePort
  ports:
    - name: "2379"
      port: 2379
      targetPort: 2379
      nodePort: 30004
  selector:
    io.kompose.service: etcd
status:
  loadBalancer: {}