apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: mongo-tenants
  name: mongo-tenants
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mongo-tenants
    spec:
      containers:
        - args:
            - mongod
            - --bind_ip
            - 0.0.0.0
          env:
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: password
            - name: MONGO_INITDB_ROOT_USERNAME
              value: tenants
          image: mongo:3.2.21-jessie
          name: mongo-tenants
          ports:
            - containerPort: 27017
          resources: {}
      restartPolicy: Always
status: {}